[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/drive/1fChvqVxqZNfNfCZazTqUf5sOMlu8IElD?usp=sharing)

# **Week 3 - Introduction to Linear Algebra & NumPy - Solutions**

## **Solution - Dot Product Problem: Wind Impact on Movement**

In [ ]:
import numpy as np

def calculate_wind_impact(walking_vector, wind_vector):
    # Calculate the dot product
    impact = np.dot(walking_vector, wind_vector)
    return impact

# Vectors for the problem
walking_vector = np.array([3, 4])
wind_vector = np.array([1, -1])

# Calculating the impact
wind_impact = calculate_wind_impact(walking_vector, wind_vector)
print("Wind Impact on Walking:", wind_impact)


## **Solution - Cross Product Problem: Calculating Perpendicular Direction**

In [ ]:
import numpy as np

def calculate_perpendicular_direction(force1, force2):
    # Calculate the cross product
    perpendicular_direction = np.cross(force1, force2)
    return perpendicular_direction

# Forces for the problem
force1 = np.array([2, 0, -1])
force2 = np.array([1, 3, 4])

# Calculating the perpendicular direction
perpendicular_direction = calculate_perpendicular_direction(force1, force2)
print("Perpendicular Direction:", perpendicular_direction)


## **Solution - Vector Magnitude and Direction**

In [2]:
import numpy as np

vector_a = np.array([3, -4])

# Calculating magnitude
magnitude = np.linalg.norm(vector_a)
print("Magnitude of vector_a:", magnitude)

# Normalizing vector_a
unit_vector = vector_a / magnitude
print("Direction (Unit Vector) of vector_a:", unit_vector)


Magnitude of vector_a: 5.0
Direction (Unit Vector) of vector_a: [ 0.6 -0.8]


## **Solution - Matrix Multiplication Using * Operator**

In [ ]:
# Exercise 1: Matrix Multiplication Using * Operator
import numpy as np

# Define the matrices
A = np.array([[1, 2], [3, 4]])
B = np.array([[4, 3], [2, 1]])

result = A * B
print("Element-wise multiplication of A and B:\n", result)

## **Solution - Matrix Multiplication Using @ Operator**

In [3]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[4, 3], [2, 1]])

result = A @ B
print("Standard matrix product of A and B:\n", result)

Standard matrix product of A and B:
 [[ 8  5]
 [20 13]]


## **Solution - Verifying the Non-Commutative Property of Matrix Multiplication**

In [4]:
A = np.array([[1, 3], [2, 5]])
B = np.array([[4, 1], [2, 3]])

result_ab = A @ B
result_ba = B @ A

print("AB:\n", result_ab)
print("BA:\n", result_ba)
print("AB equals BA:", np.array_equal(result_ab, result_ba))

AB:
 [[10 10]
 [18 17]]
BA:
 [[ 6 17]
 [ 8 21]]
AB equals BA: False
