# Introduction to NumPy

The fundamental package for scientific computing with Python: https://numpy.org/ \
(**paper**) [Nature volume 585, pages 357–362 (2020)](https://doi.org/10.1038/s41586-020-2649-2) 

**Abstract**\
Array programming provides a powerful, compact and expressive syntax for accessing, manipulating and operating on data in vectors, matrices and higher-dimensional arrays. 
NumPy is the primary array programming library for the Python language. It has an essential role in research analysis pipelines in fields as diverse as physics, chemistry, astronomy, geoscience, biology, psychology, materials science, engineering, finance and economics. 
For example, in astronomy, NumPy was an important part of the software stack used in the discovery of gravitational waves1 and in the first imaging of a black hole. 

In [1]:
import numpy as np # load numpy as np

# Arrays


[additional tutorial](https://www.learndatasci.com/tutorials/applied-introduction-to-numpy-python-tutorial/)

In [2]:
X = np.array([[1, 2], [3, 4]])  # Defining arrays

print(X)
print('X type:', type(X))


n_rows, n_cols = X.shape
print('Size:')
print('number of rows:',n_rows)
print('number of columns:', n_cols)

[[1 2]
 [3 4]]
X type: <class 'numpy.ndarray'>
Size:
number of rows: 2
number of columns: 2


Change the value of the array

```X[i,j]``` -> single element in the i-th row and j-th column\
```X[:,j]``` -> all elements in the j-th column\
```X[i,:]``` -> all elements in the i-th row

In [3]:
print('Original: \n', X)
print('X[0,0] = ', X[0,0])
X[0,0] = 10
print('Modified: \n', X)

X[:,1] = -1 #select first column
print(X)

Original: 
 [[1 2]
 [3 4]]
X[0,0] =  1
Modified: 
 [[10  2]
 [ 3  4]]
[[10 -1]
 [ 3 -1]]


## Excercises
(tips) [NumPy documentation](https://numpy.org/doc/stable/index.html)

In [4]:
# create an array full of zeros with size (10,4)


In [5]:
# create an array full of zeros with size (12,), where the element 6 has the value of 4


# The power of NumPy

Here we revise some operations we can do using Numpy

In [6]:
#load some data (Solubility from https://github.com/whitead/dmol-book/blob/main/data/curated-solubility-dataset.csv)
D = np.load('../data/solubility.npy')
print(D.shape) 

(9982,)


## Mean and standard deviation

$\mu = \frac{1}{N}\sum_i^{N} x_i$\
$\sigma =  \sqrt\frac{\sum_i^{N}{(x_i-\mu)^2}}{N}$


In [7]:
mu = np.mean(D)
print('mu = ', mu)
std = np.std(D)
print('std = ', std)

mu =  -2.8899088047869865
std =  2.368035824195331


## Exercises

Using ```np.sum()```,```np.sqrt()```, ```D.shape```, and ```np.power()``` create a function that computes the **mean** and **standard deviation** of an given array.

In [8]:
def f(x):
    mu =  # compute mean

    std =  # compute std

    return mu, std


SyntaxError: invalid syntax (2349222592.py, line 2)